#!/bin/bash
# Generated by tools/generate-e2e-replay.mjs — do not edit.
#
# Seed:         42
# Source score: 21
# Close calls:  0
# Recorded at:  2026-05-01T09:30:43.106+00:00
# Tap stream:   108 events (55 L + 53 R)
# Compensation: 65ms per tap, 10ms floor — 0 clamped, 7020ms total shaved
# Target score: >= 1 (test passes if reached)
#
# Replay only works against the matching seeded APK (EXPO_PUBLIC_E2E_SEED=42, eas.json e2e profile).
# Re-run the generator after engine-tuning changes — recorded tap timings drift relative to new physics.

set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

e2e_init "02-seeded-replay-42"
e2e_launch_app_clean

# Prime tap — any position. Engine handleTap on idle transitions to
# playing regardless of tap location, and primes both dots upward.
echo ">>> prime tap"
e2e_tap_l

echo ">>> replaying 108 captured taps"
sleep 0.072; e2e_tap_r   # tap 1/108 (delta=137ms, wait=72ms, cumulative=137ms)
sleep 0.298; e2e_tap_l   # tap 2/108 (delta=363ms, wait=298ms, cumulative=500ms)
sleep 0.287; e2e_tap_r   # tap 3/108 (delta=352ms, wait=287ms, cumulative=852ms)
sleep 0.393; e2e_tap_l   # tap 4/108 (delta=458ms, wait=393ms, cumulative=1310ms)
sleep 0.674; e2e_tap_r   # tap 5/108 (delta=739ms, wait=674ms, cumulative=2049ms)
sleep 0.491; e2e_tap_l   # tap 6/108 (delta=556ms, wait=491ms, cumulative=2605ms)
sleep 0.704; e2e_tap_r   # tap 7/108 (delta=769ms, wait=704ms, cumulative=3374ms)
sleep 0.601; e2e_tap_l   # tap 8/108 (delta=666ms, wait=601ms, cumulative=4040ms)
sleep 0.503; e2e_tap_r   # tap 9/108 (delta=568ms, wait=503ms, cumulative=4608ms)
sleep 0.733; e2e_tap_l   # tap 10/108 (delta=798ms, wait=733ms, cumulative=5406ms)
sleep 0.390; e2e_tap_r   # tap 11/108 (delta=455ms, wait=390ms, cumulative=5861ms)
sleep 0.269; e2e_tap_l   # tap 12/108 (delta=334ms, wait=269ms, cumulative=6195ms)
sleep 0.820; e2e_tap_r   # tap 13/108 (delta=885ms, wait=820ms, cumulative=7080ms)
sleep 0.410; e2e_tap_l   # tap 14/108 (delta=475ms, wait=410ms, cumulative=7555ms)
sleep 0.450; e2e_tap_r   # tap 15/108 (delta=515ms, wait=450ms, cumulative=8070ms)
sleep 0.553; e2e_tap_l   # tap 16/108 (delta=618ms, wait=553ms, cumulative=8688ms)
sleep 0.480; e2e_tap_r   # tap 17/108 (delta=545ms, wait=480ms, cumulative=9233ms)
sleep 0.537; e2e_tap_l   # tap 18/108 (delta=602ms, wait=537ms, cumulative=9835ms)
sleep 0.599; e2e_tap_r   # tap 19/108 (delta=664ms, wait=599ms, cumulative=10499ms)
sleep 0.217; e2e_tap_l   # tap 20/108 (delta=282ms, wait=217ms, cumulative=10781ms)
sleep 0.890; e2e_tap_r   # tap 21/108 (delta=955ms, wait=890ms, cumulative=11736ms)
sleep 0.292; e2e_tap_l   # tap 22/108 (delta=357ms, wait=292ms, cumulative=12093ms)
sleep 0.492; e2e_tap_r   # tap 23/108 (delta=557ms, wait=492ms, cumulative=12650ms)
sleep 0.450; e2e_tap_l   # tap 24/108 (delta=515ms, wait=450ms, cumulative=13165ms)
sleep 0.724; e2e_tap_r   # tap 25/108 (delta=789ms, wait=724ms, cumulative=13954ms)
sleep 0.496; e2e_tap_l   # tap 26/108 (delta=561ms, wait=496ms, cumulative=14515ms)
sleep 0.472; e2e_tap_r   # tap 27/108 (delta=537ms, wait=472ms, cumulative=15052ms)
sleep 0.464; e2e_tap_l   # tap 28/108 (delta=529ms, wait=464ms, cumulative=15581ms)
sleep 0.477; e2e_tap_r   # tap 29/108 (delta=542ms, wait=477ms, cumulative=16123ms)
sleep 0.453; e2e_tap_l   # tap 30/108 (delta=518ms, wait=453ms, cumulative=16641ms)
sleep 0.625; e2e_tap_r   # tap 31/108 (delta=690ms, wait=625ms, cumulative=17331ms)
sleep 0.443; e2e_tap_l   # tap 32/108 (delta=508ms, wait=443ms, cumulative=17839ms)
sleep 0.475; e2e_tap_r   # tap 33/108 (delta=540ms, wait=475ms, cumulative=18379ms)
sleep 0.424; e2e_tap_l   # tap 34/108 (delta=489ms, wait=424ms, cumulative=18868ms)
sleep 0.527; e2e_tap_r   # tap 35/108 (delta=592ms, wait=527ms, cumulative=19460ms)
sleep 0.361; e2e_tap_l   # tap 36/108 (delta=426ms, wait=361ms, cumulative=19886ms)
sleep 0.813; e2e_tap_r   # tap 37/108 (delta=878ms, wait=813ms, cumulative=20764ms)
sleep 0.375; e2e_tap_l   # tap 38/108 (delta=440ms, wait=375ms, cumulative=21204ms)
sleep 0.899; e2e_tap_r   # tap 39/108 (delta=964ms, wait=899ms, cumulative=22168ms)
sleep 0.287; e2e_tap_l   # tap 40/108 (delta=352ms, wait=287ms, cumulative=22520ms)
sleep 0.474; e2e_tap_r   # tap 41/108 (delta=539ms, wait=474ms, cumulative=23059ms)
sleep 0.402; e2e_tap_l   # tap 42/108 (delta=467ms, wait=402ms, cumulative=23526ms)
sleep 0.518; e2e_tap_r   # tap 43/108 (delta=583ms, wait=518ms, cumulative=24109ms)
sleep 0.366; e2e_tap_l   # tap 44/108 (delta=431ms, wait=366ms, cumulative=24540ms)
sleep 0.486; e2e_tap_r   # tap 45/108 (delta=551ms, wait=486ms, cumulative=25091ms)
sleep 0.379; e2e_tap_l   # tap 46/108 (delta=444ms, wait=379ms, cumulative=25535ms)
sleep 0.578; e2e_tap_r   # tap 47/108 (delta=643ms, wait=578ms, cumulative=26178ms)
sleep 0.424; e2e_tap_l   # tap 48/108 (delta=489ms, wait=424ms, cumulative=26667ms)
sleep 0.755; e2e_tap_r   # tap 49/108 (delta=820ms, wait=755ms, cumulative=27487ms)
sleep 0.248; e2e_tap_l   # tap 50/108 (delta=313ms, wait=248ms, cumulative=27800ms)
sleep 0.593; e2e_tap_r   # tap 51/108 (delta=658ms, wait=593ms, cumulative=28458ms)
sleep 0.416; e2e_tap_l   # tap 52/108 (delta=481ms, wait=416ms, cumulative=28939ms)
sleep 0.512; e2e_tap_r   # tap 53/108 (delta=577ms, wait=512ms, cumulative=29516ms)
sleep 0.412; e2e_tap_l   # tap 54/108 (delta=477ms, wait=412ms, cumulative=29993ms)
sleep 0.053; e2e_tap_l   # tap 55/108 (delta=118ms, wait=53ms, cumulative=30111ms)
sleep 0.653; e2e_tap_r   # tap 56/108 (delta=718ms, wait=653ms, cumulative=30829ms)
sleep 0.516; e2e_tap_l   # tap 57/108 (delta=581ms, wait=516ms, cumulative=31410ms)
sleep 0.617; e2e_tap_r   # tap 58/108 (delta=682ms, wait=617ms, cumulative=32092ms)
sleep 0.770; e2e_tap_l   # tap 59/108 (delta=835ms, wait=770ms, cumulative=32927ms)
sleep 0.461; e2e_tap_r   # tap 60/108 (delta=526ms, wait=461ms, cumulative=33453ms)
sleep 0.501; e2e_tap_l   # tap 61/108 (delta=566ms, wait=501ms, cumulative=34019ms)
sleep 0.125; e2e_tap_r   # tap 62/108 (delta=190ms, wait=125ms, cumulative=34209ms)
sleep 0.346; e2e_tap_l   # tap 63/108 (delta=411ms, wait=346ms, cumulative=34620ms)
sleep 0.633; e2e_tap_r   # tap 64/108 (delta=698ms, wait=633ms, cumulative=35318ms)
sleep 0.451; e2e_tap_l   # tap 65/108 (delta=516ms, wait=451ms, cumulative=35834ms)
sleep 0.544; e2e_tap_r   # tap 66/108 (delta=609ms, wait=544ms, cumulative=36443ms)
sleep 0.548; e2e_tap_l   # tap 67/108 (delta=613ms, wait=548ms, cumulative=37056ms)
sleep 0.477; e2e_tap_r   # tap 68/108 (delta=542ms, wait=477ms, cumulative=37598ms)
sleep 0.617; e2e_tap_l   # tap 69/108 (delta=682ms, wait=617ms, cumulative=38280ms)
sleep 0.429; e2e_tap_r   # tap 70/108 (delta=494ms, wait=429ms, cumulative=38774ms)
sleep 0.663; e2e_tap_l   # tap 71/108 (delta=728ms, wait=663ms, cumulative=39502ms)
sleep 0.281; e2e_tap_r   # tap 72/108 (delta=346ms, wait=281ms, cumulative=39848ms)
sleep 0.408; e2e_tap_l   # tap 73/108 (delta=473ms, wait=408ms, cumulative=40321ms)
sleep 0.625; e2e_tap_r   # tap 74/108 (delta=690ms, wait=625ms, cumulative=41011ms)
sleep 0.392; e2e_tap_l   # tap 75/108 (delta=457ms, wait=392ms, cumulative=41468ms)
sleep 0.764; e2e_tap_r   # tap 76/108 (delta=829ms, wait=764ms, cumulative=42297ms)
sleep 0.193; e2e_tap_l   # tap 77/108 (delta=258ms, wait=193ms, cumulative=42555ms)
sleep 0.820; e2e_tap_r   # tap 78/108 (delta=885ms, wait=820ms, cumulative=43440ms)
sleep 0.484; e2e_tap_l   # tap 79/108 (delta=549ms, wait=484ms, cumulative=43989ms)
sleep 0.647; e2e_tap_r   # tap 80/108 (delta=712ms, wait=647ms, cumulative=44701ms)
sleep 0.216; e2e_tap_l   # tap 81/108 (delta=281ms, wait=216ms, cumulative=44982ms)
sleep 0.451; e2e_tap_r   # tap 82/108 (delta=516ms, wait=451ms, cumulative=45498ms)
sleep 0.454; e2e_tap_l   # tap 83/108 (delta=519ms, wait=454ms, cumulative=46017ms)
sleep 0.690; e2e_tap_r   # tap 84/108 (delta=755ms, wait=690ms, cumulative=46772ms)
sleep 0.191; e2e_tap_l   # tap 85/108 (delta=256ms, wait=191ms, cumulative=47028ms)
sleep 0.832; e2e_tap_r   # tap 86/108 (delta=897ms, wait=832ms, cumulative=47925ms)
sleep 0.126; e2e_tap_l   # tap 87/108 (delta=191ms, wait=126ms, cumulative=48116ms)
sleep 1.033; e2e_tap_r   # tap 88/108 (delta=1098ms, wait=1033ms, cumulative=49214ms)
sleep 0.384; e2e_tap_l   # tap 89/108 (delta=449ms, wait=384ms, cumulative=49663ms)
sleep 0.527; e2e_tap_r   # tap 90/108 (delta=592ms, wait=527ms, cumulative=50255ms)
sleep 0.226; e2e_tap_l   # tap 91/108 (delta=291ms, wait=226ms, cumulative=50546ms)
sleep 0.465; e2e_tap_r   # tap 92/108 (delta=530ms, wait=465ms, cumulative=51076ms)
sleep 0.498; e2e_tap_l   # tap 93/108 (delta=563ms, wait=498ms, cumulative=51639ms)
sleep 0.417; e2e_tap_r   # tap 94/108 (delta=482ms, wait=417ms, cumulative=52121ms)
sleep 0.373; e2e_tap_l   # tap 95/108 (delta=438ms, wait=373ms, cumulative=52559ms)
sleep 0.753; e2e_tap_r   # tap 96/108 (delta=818ms, wait=753ms, cumulative=53377ms)
sleep 0.118; e2e_tap_l   # tap 97/108 (delta=183ms, wait=118ms, cumulative=53560ms)
sleep 1.077; e2e_tap_r   # tap 98/108 (delta=1142ms, wait=1077ms, cumulative=54702ms)
sleep 0.405; e2e_tap_l   # tap 99/108 (delta=470ms, wait=405ms, cumulative=55172ms)
sleep 0.617; e2e_tap_r   # tap 100/108 (delta=682ms, wait=617ms, cumulative=55854ms)
sleep 0.400; e2e_tap_l   # tap 101/108 (delta=465ms, wait=400ms, cumulative=56319ms)
sleep 0.428; e2e_tap_r   # tap 102/108 (delta=493ms, wait=428ms, cumulative=56812ms)
sleep 0.414; e2e_tap_l   # tap 103/108 (delta=479ms, wait=414ms, cumulative=57291ms)
sleep 0.459; e2e_tap_r   # tap 104/108 (delta=524ms, wait=459ms, cumulative=57815ms)
sleep 0.208; e2e_tap_l   # tap 105/108 (delta=273ms, wait=208ms, cumulative=58088ms)
sleep 0.522; e2e_tap_l   # tap 106/108 (delta=587ms, wait=522ms, cumulative=58675ms)
sleep 0.425; e2e_tap_r   # tap 107/108 (delta=490ms, wait=425ms, cumulative=59165ms)
sleep 0.333; e2e_tap_l   # tap 108/108 (delta=398ms, wait=333ms, cumulative=59563ms)

# Wait for run_end + analytics flush. The dots will likely die at or
# shortly after the last tap (replay ends, no more input → gravity).
echo ">>> waiting for death + analytics flush"
sleep 4
sleep "$ANALYTICS_FLUSH_WAIT_S"

# Verify: a run_end event with score >= target landed since test start.
# Source run scored 21; target is intentionally lower to
# absorb timing-drift attrition over the replay.
e2e_assert_run_end_score 1

e2e_pass "replay reached score >= 1"
